version: '3'
services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/cert/:/etc/ssl/
    container_name: myweb-proxy
    depends_on:
      - web

  web:
    image: pjm1024cl/flask-test
    ports:
      - 5000:5000
    container_name: myweb-web